[build]
  base = "mobile"
  command = "npm ci && timeout 600 npx expo export --platform web --output-dir dist"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  EXPO_CLI_VERSION = "6.3.10"
  CI = "true"
  EXPO_NO_CACHE = "false"

[dev]
  base = "mobile"
  command = "npm start"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
