# Netlify configuration for Bingo Nights Web Admin
# This builds the React admin dashboard

[build]
  base = "web-admin"
  command = "npm ci && npm run build"
  publish = "dist"
  ignore = "git diff --quiet HEAD^ HEAD -- web-admin/"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "true"

[dev]
  base = "web-admin"
  command = "npm run dev"
  port = 5173

# Production context - only build on main branch
[context.production]
  base = "mobile"
  command = "npm ci && timeout 600 npx expo export --platform web --output-dir dist"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
