[build]
  base = "mobile"
  command = "npm run build:web"
  publish = "dist"

[dev]
  base = "mobile"
  command = "npm start"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
