# Netlify configuration for Bingo Nights Mobile App
# This builds the Expo React Native web export

[build]
  base = "mobile"
  command = "npm ci && timeout 600 npx expo export --platform web --output-dir dist"
  publish = "dist"
  ignore = "git diff --quiet HEAD^ HEAD -- mobile/"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  EXPO_CLI_VERSION = "6.3.10"
  CI = "true"
  EXPO_NO_CACHE = "false"

[dev]
  base = "mobile"
  command = "npm start"
  port = 3000

# Production context - only build on main branch
[context.production]
  base = "mobile"
  command = "npm ci && timeout 600 npx expo export --platform web --output-dir dist"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
