[build]
  command = "echo 'Simple HTML admin - no build needed'"
  functions = "web-admin/netlify/functions"
  publish = "web-admin"

[dev]
  command = "cd web-admin && python -m http.server 3000"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
